version: "3.9"

services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=dev
    restart: "always"
    ports:
      - 8080:8080
    depends_on:
      - database

    environment:
      DATABASE_DSN: "user:password@tcp(database:3306)/unkey"
      UNKEY_WORKSPACE_ID: "${UNKEY_WORKSPACE_ID}"
      UNKEY_API_ID: "${UNKEY_API_ID}"
      UNKEY_APP_AUTH_TOKEN: "${UNKEY_APP_AUTH_TOKEN}"
      UNKEY_KEY_AUTH_ID: "${UNKEY_KEY_AUTH_ID}"

  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "unkey"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - 3306:3306
