name: Deploy semantic cache

on:
  push:
    branches:
      - semantic-cache

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Build
        run: pnpm turbo run build --filter='./packages/cache'
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3.0.0
        with:
          version: latest
      - name: Install
        uses: ./.github/actions/install
      - name: Deploy
        run: wrangler deploy src/index.ts
        working-directory: packages/semantic-cache
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

