name: Integration

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # every day at midnight

jobs:

  integration:
    name: Integration
    runs-on: ubuntu-latest

    services:
      # mysql:
      #   image: mysql:latest
      #   env:
      #     MYSQL_ALLOW_EMPTY_PASSWORD: yes
      #     MYSQL_DATABASE: unkey
      #   ports:
      #     - 3306:3306
      #   options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3


      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20.0

      - name: Set up gotestfmt
        run: go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest

      - name: Install dependencies
        run: go mod download
        working-directory: apps/agent

      - name: Start Database
        run: docker-compose up -d database
        working-directory: apps/agent

      - name: Load Schema into MySQL
        run: mysql -h 127.0.0.1 --port 3306 -uroot unkey < ./apps/agent/pkg/database/schema.sql

      - name: Bootstrap
        run: go run . bootstrap --out=.env
        working-directory: apps/agent
        env:
          DATABASE_DSN: root@tcp(localhost:3306)/unkey

      - name: Start Database
        run: docker-compose up -d agent
        working-directory: apps/agent
        env:
          DATABASE_DSN: root@tcp(localhost:3306)/unkey
          UNKEY_APP_AUTH_TOKEN: "not-used"

      - name: Test
        run: go test -v -json -shuffle=on --race ./integration/... | gotestfmt
        working-directory: apps/agent
        env:
          UNKEY_BASE_URL: http://localhost:8080
          DATABASE_DSN: root@tcp(localhost:3306)/unkey
