name: Integration

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *" # every day at noon UTC

jobs:

  integration:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20.0

      - name: Set up gotestfmt
        run: go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest

      - name: Install dependencies
        run: go mod download
        working-directory: apps/agent

      - name: Build
        run: docker compose build
        working-directory: apps/agent

      - name: Start Database
        run: docker compose up -d database && sleep 10
        working-directory: apps/agent


      - name: Load Schema into MySQL
        run: mysql -h 127.0.0.1 --port 3306 --user=user --password=password --database=unkey < ./apps/agent/pkg/database/schema.sql

      - name: Bootstrap
        run: |
          go run . bootstrap --out=.env
          for line in $(cat .env); do
             echo line >> $GITHUB_ENV
          done
        working-directory: apps/agent
        env:
          DATABASE_DSN: user:password@tcp(127.0.0.1:3306)/unkey

      - name: Start Agent
        run: docker compose up -d agent && sleep 10
        working-directory: apps/agent
        env:
          DATABASE_DSN: user:password@tcp(127.0.0.1:3306)/unkey
          UNKEY_APP_AUTH_TOKEN: "not-used"

      - name: Test
        run: go test -v -json -shuffle=on --race ./tests/integration/... | gotestfmt
        working-directory: apps/agent
        env:
          UNKEY_BASE_URL: http://localhost:8080
          DATABASE_DSN: user:password@tcp(127.0.0.1:3306)/unkey

      - name: Stop containers
        if: always()
        run: docker-compose down
        working-directory: apps/agent
